### ISSUE TITLE
utf-8 issue in Python.

### ISSUE THREAD

**Issue by Salamandar** [XtremeDevX/electric#16]
**Describe the bug**
utf-8 issue on almost every command
```
PS C:\Users\Moi> electric install firefox
SuperCached [ Mozilla Firefox ]
██████████████████████████████  56.6 / 56.6 MB
Verified Installer Hash
Installing Mozilla Firefox
Traceback (most recent call last):
  File "electric.py", line 2386, in <module>
  File "click\core.py", line 829, in __call__
  File "click\core.py", line 782, in main
  File "click\core.py", line 1259, in invoke
  File "click\core.py", line 1066, in invoke
  File "click\core.py", line 610, in invoke
  File "click\decorators.py", line 21, in new_func
  File "electric.py", line 467, in install
  File "utils.py", line 1553, in get_pid
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x82 in position 57: invalid start byte
[2736] Failed to execute script electric
PS C:\Users\Moi>
```

**To Reproduce**
Any command triggers the bug.

**Expected behavior**
No error.

**Desktop (please complete the following information):**
 - OS: windows 10
 - Version 1.0.0

**Comment by XtremeDevX** [comment]
Weird. It seems you are getting non-utf 8 output when running `tasklist` on your shell

**Comment by Salamandar** [comment]
probably due to accents. I'm french.
And windows rarely uses utf-8.

**Comment by Salamandar** [comment]
Yeah, looks like the 57th char of tasklist output is a 'é'.
```
PS C:\Users\Moi> tasklist

Nom de l’image                 PID Nom de la sessio Numéro de s Utilisation
========================= ======== ================ =========== ============
System Idle Process              0 Services                   0         8 Ko
System                           4 Services                   0     3 380 Ko
Registry                       148 Services                   0    22 372 Ko
smss.exe                       528 Services                   0       340 Ko
csrss.exe                      684 Services                   0     2 332 Ko
[...]
```

**Comment by Salamandar** [comment]
Still relevant !

**Comment by Salamandar** [comment]
Well I guess this project is dead.

**Comment by Salamandar** [comment]
@XtremeDevX I see you deleted my comment. I was just stating the obvious :/

**Comment by XtremeDevX** [comment]
@Salamandar Apologies for not getting this fixed earlier, I'll work on at as soon as I can, this is not an acceptable bug.
